version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::810102036360:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-NNU3SM6F19YP"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::810102036360:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1574HYML7S2LZ"
cloudformation_execution_role = "arn:aws:iam::810102036360:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-1XKXGJSDE2MDT"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-325qtlnr4zxc"
image_repository = ""
region = "us-east-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::810102036360:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-56V3YLW3P04M"
cloudformation_execution_role = "arn:aws:iam::810102036360:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-1GKN69D75X1WO"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-1g400gyf0sb5z"
image_repository = ""
region = "us-east-1"
